version: '3.3'

services:
  utils:
    image: ignitial/utils:${SVC_VERSION}
    container_name: utils
    ports:
      - ${IIOS_DOCKER_EXPORTED_PORTS}
    environment:
      - IIOS_REDIS_HOST=redis
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - IIOS_SERVER_HOST=utils
      - IIOS_SERVER_PORT=${IIOS_SERVER_PORT}
    networks:
      infra:

networks:
  infra:
    external: true
